### ISSUE TITLE
Jackpot doesn't Work

### ISSUE THREAD

**Issue by VanilaBOI** [MoonJuiceDev/BuyRateSettings#2]
Buyrate jackpot ist never synced and only one person ever has it(client or host).

So whenever someone gets the Jackpot Alert(even if it's the host) it's never truly the actual buyrate.

**Comment by MoonJuiceDev** [comment]
I've been unable to replicate this issue - all RNG is based off of `StartOfRound.Instance.randomMapSeed` so it should be identical for all players since everyone is on the same seed. It should also maintain the same rates when reopening the game as you'd still be on the seed that you left on.

However, the mod doesn't have config syncing and my guess is that someone in your lobby had different config values, resulting in mismatched rates. Are you able to confirm if that's the case?

I may look into config syncing to avoid this happening in the future.

**Comment by VanilaBOI** [comment]
Impossible, I always share my profile code with my friends before every session
Im guessing it's a mod incompatibility

**Comment by MoonJuiceDev** [comment]
Could you share your profile code so I can look for incompatibilities?

**Comment by VanilaBOI** [comment]
018d1dfc-a819-12d5-73e2-5de62f0205ad

**Comment by MoonJuiceDev** [comment]
I may have figured it out, I think it was an oversight on my part. One of the conditions for determining if you get a jackpot or not was using `DateTime.Now.Millisecond`, causing the rate result to be different because it would get triggered milliseconds later than it was triggered for another player. I didn't get the issue on smaller modpacks, but larger modpacks seem to cause a very slight desync between players due to all the extra stuff going on.

I've changed the condition to utilize the map seed instead, so _all_ RNG should be seed dependent in the next update. I'm also getting config syncing setup so I'll have an update ready soon. Thank you for reporting this!
